name: Release

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - arch: x86
            compiler: i686-w64-mingw32-gcc
            output: SomeTweaksPlugin-win32.dll
          - arch: x64
            compiler: x86_64-w64-mingw32-gcc
            output: SomeTweaksPlugin-win64.dll

    steps:
      - uses: actions/checkout@v4

      - name: Clone ClassiCube
        run: git clone https://github.com/ClassiCube/ClassiCube.git

      - name: Build
        shell: bash
        run: |
          ${{ matrix.compiler }} \
            -shared -O3 \
            -Isrc \
            src/*.c \
            -o ${{ matrix.output }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ matrix.arch }}
          path: ${{ matrix.output }}

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: x86
            package: gcc-multilib
            cflags: -m32
            output: SomeTweaksPlugin-linux32.so
          - arch: x64
            package: gcc
            cflags: -m64
            output: SomeTweaksPlugin-linux64.so

    steps:
      - uses: actions/checkout@v4

      - name: Clone ClassiCube
        run: git clone https://github.com/ClassiCube/ClassiCube.git

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install ${{ matrix.package }}

          if [ "${{ matrix.arch }}" = "x86" ]; then
            sudo apt-get -y install libc6-dev-i386
          fi

      - name: Build
        run: |
          gcc \
            ${{ matrix.cflags }} \
            -shared -fPIC -O3 \
            -Isrc \
            src/*.c \
            -o ${{ matrix.output }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.arch }}
          path: ${{ matrix.output }}

  macos:
    runs-on: ${{ matrix.runs_on }}
    strategy:
      matrix:
        include:
          - arch: x64
            runs_on: macos-13
            output: SomeTweaksPlugin-macos-x64.dylib
          - arch: arm64
            runs_on: macos-14
            output: SomeTweaksPlugin-macos-arm64.dylib

    steps:
      - uses: actions/checkout@v4

      - name: Clone ClassiCube
        run: git clone https://github.com/ClassiCube/ClassiCube.git

      - name: Build
        run: |
          clang \
            -dynamiclib -O3 \
            -Isrc \
            src/*.c \
            -o ${{ matrix.output }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{ matrix.arch }}
          path: ${{ matrix.output }}
