name: Windows Release

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Clone ClassiCube
      run: git clone https://github.com/ClassiCube/ClassiCube.git

    - name: Build
      run: |
        sudo apt-get -y install gcc-mingw-w64-i686
        mkdir -p build/release
        i686-w64-mingw32-gcc -shared -O3 -s -Isrc src/*.c -o build/release/SomeTweaksPlugin.dll

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: build/release/SomeTweaksPlugin.dll
